### ISSUE TITLE
duplicate function definitions

### ISSUE THREAD

**Issue by sandervandorsten** [victorvdb/pokemon#1]
(This is not a real problem but I'm just nitpicking for learning purposes of you getting a code review + having to resolve a github issue. @victorvdb  I know you've been programming for longer so you don't need to resolve it of course if you feel it's redundant)

Hi Victor,

I've reviewed your code in `pokemon.ipynb`. Structure and code look good and understandable! I have a small suggestion. 

You define the function `filter_rows()` multiple times in your notebook; where only the `keep_columns` value is different. I'd suggest to make this an argument to the function as to keep only 1 definition of the function, yet make it parametrizable. 

Let me know if you agree with the proposed changes. We can close the issue once it has been changed; or we've come to a different agreement. Thanks!

**Comment by victor** [comment]
please close the issue @sandervandorsten . I don't know what this is about

**Comment by victorvdb** [comment]
> please close the issue @sandervandorsten . I don't know what this is about

Sander mistakenly used the wrong @. No worries @victor :-)

**Comment by sandervandorsten** [comment]
Updated the link, sorry. Wrote the review from my phone if I remember correctly, hence the mistake!
